### ISSUE TITLE
Horizontal dropdown menu stuck on 'display:block' on page load

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#1]
Example:
http://dib.uky.edu/provost/unitsdepartments

**Comment by cornettims** [comment]
This is on the 'main menu' I think? The parent items are not expected to have destinations:
Parent Link - has no destination, has children
This is I think described in the text underneath 'main menu' -- we can probably strip out 'active' from parent level items that DO have destinations, though. 
The reason parents shouldn't have destinations may be more apparent when configured for a vertical menu -- the expand/collapse component the design calls for creates that trade off. (Also mobile implications.)

**Comment by ashooner** [comment]
OK, I did not realize this behavior. 

So I understand correctly, a site's top-level section navigation item will be inactive if it has children, and require a duplicate submenu item to function as a link? 

For example, a school has an "Academics" section, with 'undergraduate', 'graduate' etc. pages beneath it. We will  need to add "Academics" as a duplicate sibling item to those child pages in order to provide a link to an academics section landing page, like this:

Academics (no link)
--Academics (Academics section landing page)
--Undergraduate (subpage of Academics section)
--Graduate (subpage of Academics section)

Honestly, this seems pretty counterintuitive for users and content authors.

**Comment by ashooner** [comment]
This module implements an opt-in to non-active menu items:

https://drupal.org/project/special_menu_items

**Comment by cornettims** [comment]
We agree about it not being exactly intutitive -- the 'main menu' help text is one of the longest on the whole system (11 bullet points). Your module is probably worth exploration.. we want to be careful because we really do want to make sure the nav/ui is not 'hover' dependent anywhere. Click&hover to expand, click to navigate. The hover to expand, click to navigate on parents is not a good experience from a user experience perspective, either. 

But for menu items that do not have child items, it is perfectly fine for parents to have a destination. Should we explore using this module as an alternative, and update the main menu helptext to reflect creating these kinds of entries?

**Comment by ashooner** [comment]
This is a broader question, and I think it would best be flagged as an enhancement. I have that module installed, so I don't think it will block the Provost project, anyway. I'll close this bug and open another issue for discussion.
