### ISSUE TITLE
Contentlist View: Vertically align 'view details' buttons

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#13]
The CTA buttons in the contentlist view to not align vertically. Ideally they would be the same height from the bottom of the row.

**Comment by petervcook** [comment]
I may need some further clarification on this one too. All of the buttons appear to be 8 pixels from the bottom of the preceding paragraph. I don't think we would want them to be aligned with the bottom of the row incase one of the elements of the row has lots of text and the other item in the row had very little text. It could even be visually confusing for the end user if the CTA is closer to the next row than then content it its own row. See the quick example attached:
![screen shot 2013-10-28 at 3 27 26 pm](https://f.cloud.github.com/assets/1581227/1423200/30d3c73a-4007-11e3-9d8a-1a1010083c8b.png)

**Comment by ashooner** [comment]
This is subjective; to me your mock-up looks better. If we're going to put the links inline, my preference would be for simple text rather than buttons. In the Provost content they are just somewhat offset, which I think looks messy.

**Comment by cornettims** [comment]
We changed the links to text instead of buttons and just left them inline. Since we are no longer using a table as a layout for the view, it's difficult and hackish to get the links position absolutely at the bottom of the row (since they're now block elements, they cascade vertically rather than having a fixed height like you'd see in a table cell).
