### ISSUE TITLE
Vertically center banner 'header text' field output.

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#16]
For the Provost site it looks uncentered, and would probably look worse if less text was entered.

See this article for one technique:
http://css-tricks.com/vertically-center-multi-lined-text/

**Comment by cornettims** [comment]
That technique only works 100% when you have a fixed height div. Because it's a responsive (percentage based) layout, that doesn't quite work (since the content will cascade vertically based on the window width). What we did to overcome that was use a min-height attribute at the break points so it will vertically center based on that value. That's probably the closest approximation we can get using a responsive layout.

Those changes are in the latest commit and will show up as soon as it's pulled.
