### ISSUE TITLE
Window 7/Chrome: upper left 'uky.edu' renders incorrectly

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#20]
This appears to be a font rendering issue:

![top left uky link](https://f.cloud.github.com/assets/58358/1473947/94dddf30-4625-11e3-81c4-1fbe0c7e7c44.PNG)

**Comment by petervcook** [comment]
Hum, that's tricky. If it's font rendering we're kind of at the mercy of the OS. 
4 things we could try:
- Make uky.edu lowercase
- Try bold
- Make the font size 1px larger
- use an image, would wouldn't be my first choice for obvious accessibility reasons.

Andy, since I assume you are seeing this on your own machine, could you do web inspector tests of those first 3 solutions and see if they make the link more readable?

**Comment by petervcook** [comment]
Also, just FYI with how that top bar works:
Currently, there is a json include file that is part of the local theme. 

The long term goal is to put that somewhere globally, (Probably on the uky.edu www server.) so that any department can pull in the pre-header dynamically. 

All UKIT/PR will need to do is edit the theme to point to a url instead of a local file. Where it is now is as far as we can take it by ourselves.

**Comment by ashooner** [comment]
Sorry, I’m not seeing it; I’m on a Mac. I had it reported by 2 other people. Are you unable to replicate it in your browser test suite?

Andy Shooner
University Web Manager
University of Kentucky Public Relations & Marketing
Lexington, Ky. 40506-0047
859-257-5370

On Nov 5, 2013, at 10:53 AM, petervcook <notifications@github.com<mailto:notifications@github.com>> wrote:

Hum, that's tricky. If it's font rendering we're kind of at the mercy of the OS.
4 things we could try:
-   Make uky.eduhttp://uky.edu lowercase
-   Try bold
-   Make the font size 1px larger
-   use an image, would wouldn't be my first choice for obvious accessibility reasons.

Andy, since I assume you are seeing this on your own machine, could you do web inspector tests of those first 3 solutions and see if they make the link more readable?

**Comment by petervcook** [comment]
Sorry, I was thinking you were on Windows as your main machine. (long story: I thought you had said at our first meeting that you use an iPad, but a Windows machine. But thinking back on it now, I think it probably was that you use an iPad and an Android phone)

Anyway, yes I am seeing this on our testing PC. I was able to find that just changing the font from "HelveticaNeue-Roman" to "helvetica" fixed it up!
