### ISSUE TITLE
More granular control over inline image styling

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#30]
- Add th ability to choose border vs. no border. (not sure on interface for this)
- Add proper margins for floated images. (0 margin for the side it's floated to).

**Comment by petervcook** [comment]
Good catch on the floated images thing. 
For the border or no boarder control. I assume we need something more obvious than a CSS class? I wonder if we could add a button to the WYSIWYG editor.

**Comment by petervcook** [comment]
Hi Andy,
http://dib.uky.edu/provost/style-test
This is just a test page we made to see what's going on with the image styles.

We are working to change the margin on floated images. Could you provide us a little bit more detail on what you are looking for from a border standpoint?

By default images have no border. However, using the WYSIWYG editor if you add an image into the body (using the insert module) and then highlight the image, you can click on the image settings to edit it's attributes including border.

**Comment by petervcook** [comment]
We added some css rules to target images in the body that are floated left/right. It looks like this:

.field-name-body img[align="left"],
.field-name-body img[style*="float: left"] {

```
margin: 1em 1em 1em 0;
```

}

We believe this is a good solution because it doesn't require any extra steps when authoring content once you set the alignment/float. It works great in IE9+, webkit, gecko, iOS and Android browsers. IE8 and below doesn't support this type of selector, but it's a pretty graceful degradation. The alternative for IE8 would be to require a specific class be applied to the image.

**Comment by ashooner** [comment]
This all looks great. Thanks!
