### ISSUE TITLE
Use Horizontal Menu implemented?

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#4]
Is the option to turn off horizontal menus implemented? I did not see any rendering change when setting it to 'no' on the Provost site.

**Comment by cornettims** [comment]
This is implemented; you can move the menu between regions. The menu structure changed a bit in the last iteration -- we probably need to make it more clear and maybe programmatically print the menu in either the sidebar region or the horizontal region. When the menu is horizontal, and you have a lot of items, we had to 'munge' the menu output a bit to get it to work. This wasn't necessary if you elected to put the menu in the sidebar. So that is really what this option is about. Did you have any trouble moving the menu to a different region? 

To make it more user friendly, we'll probably just change it to print programmatically in a region depending on the theme setting?

**Comment by ashooner** [comment]
Ok thanks, that makes sense. I guess I was expecting that option to
actually reposition the menu. I wonder if this is related to the other
issue about the submenu being stuck on display:block?
